#!/usr/bin/env lua

local logger = require("nixio")
local jsonc = require("luci.jsonc")

local function log_msg(priority, msg)
	local pid
	local sys_msg

	pid = logger.getpid()
	sys_msg = string.format("%s (%s) vendor: %s", os.date(), pid, msg)
	logger.syslog(priority, sys_msg)
end

local function err(msg)
	log_msg("err", msg)
end

local function warning(msg)
	log_msg("warning", msg)
end

local function info(msg)
	log_msg("info", msg)
end


local function ip_get_Hosts_table()
	local iptable
	local json
	local f
	local success

	f = io.popen("ubus call luci-rpc getHostHints")
	json = f:read("*a")
	success, iptable = pcall(jsonc.parse, json)

	if not success then
		err(string.format([[Error while parsing ip route.]]))
		f:close()
	end
	f:close()
	return iptable
end

local function perform_lookup(ips)
	local mac_list
	local f
	local cmd = [[
		awk '{print $1, $2}' | while read ip device; do
			arp-scan -I $device $ip --plain
		done
	]]

	mac_list = {}

	for i,j in pairs(ips) do
		f = io.popen(string.format("echo %s %s| %s", j.ip, j.dev, cmd))

		for line in f:lines() do
			local mac
			local vendor

			mac = string.match(line, "%x%x:%x%x:%x%x:%x%x:%x%x:%x%x")
			vendor = string.match(line, ".*%c(.*)$")

			if vendor then
				mac_list[mac] = vendor
			end
		end
		f:close()
	end

	return mac_list
end

local function create_mac_table(tab)
	local mac_list
	local vendor_table
	local count
	local ips = {}
	local f
	local device

	f = io.popen("ip r s|awk '{print $3}'")

	for line in f:lines() do
		device = line
	end

	f:close()

	for i,j in pairs(tab) do
		if j.ipaddrs[1] then
			table.insert(ips, {ip=j.ipaddrs[1], dev=device})
		end
	end

	vendor_table = perform_lookup(ips)

	mac_list = {}
	count = 1

	for i,j in pairs(tab) do
		table.insert(mac_list,
			{ lladdr = i, vendor = "",
			 ip4 = "", ip6 = "", name = ""})

		if j.ipaddrs then
			mac_list[count].ip4 = j.ipaddrs[1]
		end

		if j.ip6addrs then
			mac_list[count].ip6 = j.ip6addrs[1]
		end

		if j.name then
			mac_list[count].name = j.name
		end

		if vendor_table[i:lower()] then
			mac_list[count].vendor = vendor_table[i:lower()]
		elseif i:match("^00:01:49.*$") then
			mac_list[count].vendor = "TDT AG"
		end

		count = count + 1
	end
	return mac_list
end

local function main()
	local content
	local mac_list 

	content = ip_get_Hosts_table()
	mac_list = create_mac_table(content)
	print(jsonc.stringify(mac_list))
end

main()
